name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 16 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: metrics
        uses: lowlighter/metrics@latest
        with:
         filename: metrics.base.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: header, activity, community, repositories, metadata
         
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
         filename: metrics.plugin.isocalendar.fullyear.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_isocalendar: yes
         plugin_isocalendar_duration: full-year

      - name: stargazers
        uses: lowlighter/metrics@latest
        with:
         filename: metrics.plugin.stargazers.chartist.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_stargazers: yes
         plugin_stargazers_charts_type: chartist
         
      - name: Most used languages
        uses: lowlighter/metrics@latest
        with:
         filename: metrics.plugin.languages.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_languages: yes
         plugin_languages_details: bytes-size, percentage
